export type OptionKey = "A" | "B" | "C" | "D"
export const OPTION_KEYS: OptionKey[] = ["A", "B", "C", "D"]

// Where a question sits in its source PDF (generated by pdf_refs.py at the repo root).
// A region is [page (1-based), x0, y0, x1, y1], as fractions of the page size from the top left.
export type PdfRegion = [number, number, number, number, number]

export interface PdfRef {
  q: PdfRegion[] // the question and its options
  s?: PdfRegion[] // its worked solution
  p?: PdfRegion[] // the passage or table it shares with neighbouring questions
}

export interface Question {
  id: string
  year: string
  paper: string
  q_num: number
  question: string
  options: Record<OptionKey, string>
  answer: string
  solution: string
  unit: number
  unit_name: string
  conceptName: string
  pdf: PdfRef | null
  // Progress, from the latest attempt
  isAnswered: boolean
  isCorrect: boolean
  userAnswer: string | null
  lastAttemptAt: string | null
  attemptCount: number
  // Bookmark
  bookmarked: boolean
  note: string
}

export type AttemptSource = "quiz" | "swipe" | "weightage" | "repeats" | "bank"

export type QuizMode = "practice" | "mock" | "custom" | "smart" | "review"

export interface SessionSummary {
  id: string
  date: string
  mode: QuizMode
  title: string | null
  unit: number | null
  unitName: string | null
  paper: string | null
  score: number
  total: number
  duration: number | null
}

export interface DailyActivity {
  date: string // YYYY-MM-DD, server local time
  attempts: number
  correct: number
  time: number // seconds
}

export interface UnitStats {
  total: number
  attempted: number // unique questions attempted
  mastered: number // unique questions whose latest attempt is correct
  attempts: number
  correct: number
}

export interface ConceptStats {
  unit: number
  name: string
  total: number
  attempts: number
  correct: number
}

export interface Stats {
  totals: {
    questions: number
    attempted: number
    mastered: number
    mistakes: number
    attempts: number
    correct: number
    sessions: number
    time: number
    bookmarks: number
  }
  daily: DailyActivity[]
  units: Record<number, UnitStats>
  concepts: ConceptStats[]
  history: SessionSummary[]
}
